### ISSUE TITLE
speed up and slow down option

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#2]
**Describe the solution you'd like**
i should be able to speed up or slow down howevet fast i want, not just 2x or 3x but 10x even using a slider

**Comment by Aga-C** [comment]
@RustoMCSpit Please be more descriptive, not just paste an old text into the one chosen header from the template.

Do you mean playback? Why would you need it? What's the use case? Why can't it be done in an external app, leaving this just a simple Voice Recorder?

It's the same for other issues, please be more specific.

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/204
