### ISSUE TITLE
Audio formats / extensions used (make compliant with modern standards)

### ISSUE THREAD

**Issue by osering** [FossifyOrg/Voice-Recorder#28]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Right now there is file Extensions (following codec, not indicating container):
(o) m4a
(  ) mp3
(  ) ogg (Opus)

Problem: 
1) container mp4 with extension m4a can contain 2 codecs: AAC (loose) or ALAC (looseless). ALAC is considered better. Which one is used?
2) container ogg is very popular and can contain Vorbis, Dirac, Opus and other codecs. How can someone afterwards identify which one is used in this ogg? Specially for this .opus extension has been officially registered (probably in 2018), so the file with opus codec has .opus extension as this is modern and all major operating systems recognize it.

https://wiki.xiph.org/MIME_Types_and_File_Extensions#.opus_-_audio.2Fogg
https://en.m.wikipedia.org/wiki/Opus_(audio_format)#cite_note-MIME-and-FileExt-1
So the codec is Opus, and the container format is Ogg, but the "official" file extension is .opus. 3 different things.

https://en.m.wikipedia.org/wiki/MP4_file_format

Offered change:
(  ) m4a (mp4, acc or alac) 128
(  ) mp3 128
(o) opus (ogg, opus) 128

Now default choice is m4a. If acc used instead of alac in it, opus could be made as default choice, as it generally performs better than order aac codec.
P.S. Also indicate bitrate (kbps) used for each.

### Why do you want this feature?

Make it more clear and standard compliant.

**Comment by Aga-C** [comment]
There are multiple requests. Please split it into separate issues.

**Comment by David-Else** [comment]
In my opinion opus should be the default choice.

https://opus-codec.org/
https://opus-codec.org/release/stable/2023/04/20/libopus-1_4.html
https://developer.android.com/media/platform/supported-formats

Sorry I am not an Android dev, I just know about the amazing high quality of opus.
