### ISSUE TITLE
Tag recordings

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#3]
**Describe the solution you'd like**
It would be helpful if one could tag recordings e.g. TODO, Lecture, etc.

**Additional Context**
tags should have custom hex colors btw and we should be able to sort by tag and even be able to place tagged recordings specifically into a different file directory if wanted when exporting audios

this should also add a downloadable markdown file that contains the names of what files are under what tags

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/201
