### ISSUE TITLE
Bookmark support

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#4]
**Describe the solution you'd like**
It would be great if this app has bookmark support.

A way to add bookmarks while recording and playback.
Import/export bookmarks in a format that will allow easy exchange of bookmarks between other applications.

**Comment by inson1** [comment]
@RustoMCSpit title :) PS no need responding, I will delete comment after the change

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by Aga-C** [comment]
> Import/export bookmarks in a format that will allow easy exchange of bookmarks between other applications.

Do you have any particular format or other apps in mind?

**Comment by RustoMCSpit** [comment]
> > Import/export bookmarks in a format that will allow easy exchange of bookmarks between other applications.
> 
> Do you have any particular format or other apps in mind?

Markdown?

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/6
