### ISSUE TITLE
Stereo Audio Output

### ISSUE THREAD

**Issue by qmro** [FossifyOrg/Voice-Recorder#42]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please add the option to record and output the recordings in stereo for devices that support it.

### Why do you want this feature?

In many cases it allows for specific sounds to be more audible and voices easier to hear and more distinguishable from other sounds or from other peoples' voices (in the case of a meeting with multiple people).

**Comment by Aga-C** [comment]
Try different options in `Audio source` setting, one of them should record in stereo on your device. If it records in stereo, please let us know which one worked for you.

**Comment by naveensingh** [comment]
@Aga-C I think stereo audio recording is not implemented.
