### ISSUE TITLE
Visual feedback to indicate recording being stopped and processed

### ISSUE THREAD

**Issue by Cwpute** [FossifyOrg/Voice-Recorder#49]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When a recording is stopped, reset the waveform preview and record time, and when a recording is being processed, show a toast message saying what's happening.
Alternatively you could have a "loading" icon appear somewhere (instead of the play button?) if you can't record anything while something else is processed.

### Why do you want this feature?

When you stop the recording, nothing tells the user that their recording has been saved or either processed, quite the contrary: the screen looks just like when you pause a recording. It makes it-impossible to know without practice if the app acted as expected or not.
My own use case was sending an audio message by SMS (via Fossify SMS): when i stopped the recording, it would just hang for about 5 seconds, then automatically quit and get back to Fossify SMS with my recording ready. If i didn't know any better, i would have thought the app behaved badly, didn't save the recording or that i made a mistake, and may have quitted the app myself or try to record again.

**Comment by Aga-C** [comment]
> show a toast message saying what's happening
(...)
When you stop the recording, nothing tells the user that their recording has been saved

But there is a toast message saying that recording has been saved. It sounds more like your phone became unresponsive for a moment, and that's why it haven't shown a toast from the app. It seems to be related to this performance issue: https://github.com/FossifyOrg/Voice-Recorder/issues/22.

**Comment by Cwpute** [comment]
There indeed is a toast message, somehow it eluded me, sorry.
But the fact i didn't register it after having used Fossify's audio recorder since it was published on the Fdroid store shows that it is easily obscured by other things happening on the screen. It shows this toast message is not enough.

The second part of my suggestion, acting on the waveform visualizer, would at least reset the main aspect of the record screen to how it is before any recording starts.

Regarding my specific use case i'll try to record a video of what happens to more clearly show you the problem.

**Comment by Cwpute** [comment]
https://github.com/FossifyOrg/Voice-Recorder/assets/80604512/f061b20f-9a30-410f-86c9-1b97feaf3843

As you can see here the audio recorder hangs for almost 4 seconds during which nothing happens, nothing is shown on the screen. Unknowing users might think the recording failed and try to switch apps, go back etc... and lose themselves while the recorder is actually doing its job.
Again, removing the waveform and showing a animated loading icon somewhere would at least reassure us the app is working and not stuck or something.

**Comment by Aga-C** [comment]
We already have a feature request raised to have progress dialogs in all apps, so this could help in your case. See: https://github.com/FossifyOrg/General-Discussion/issues/120.

**Comment by Cwpute** [comment]
This would help indeed.
Meanwhile, could you reopen this issue so the state of this issue is correctly represented ?
