### ISSUE TITLE
Renaming a file is really slow

### ISSUE THREAD

**Issue by Cwpute** [FossifyOrg/Voice-Recorder#55]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Voice-Recorder/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Nokia TA-1157

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Have a long list of previously recorded files (68 in my case, see additional info for more on this).
2. Rename a file
3. See how long it takes for the app to do it

### Expected behavior

Renaming a file should be fast and uneventful, whatever you list of previously recorded files is.

### Actual behavior

If you have a long list of recordings, renaming a file makes the app lag extremely, even as to trigger a system message saying the app is unresponsive. In my case, it takes up to 18 seconds.

### Additional information

My record folder contains 68 files for a total of 55,8 MB. They are all .m4a files created with VoiceRecorder.
Although when selecting this folder through VoiceRecorder, it only counts and lists 17 files, vhich may constitute a piece of the answer (or may be worth anwther issue entirely).

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/FossifyOrg/Voice-Recorder/issues/22.

**Comment by nekohayo** [comment]
I was about to report this same issue. Can we reopen this? In https://github.com/FossifyOrg/Voice-Recorder/issues/22#issuecomment-2571366426 over a year ago @naveensingh said "It should be fixed in the next update.", but I'm definitely still seeing this on version 1.7.1 (from F-Droid), on a powerful phone (Pixel 7).

Renaming seems broken because it does not refresh the filename in the list until a very long time after you've done it, even with just about 50 to 70 recordings in the list.

**Comment by marvinctl** [comment]
The slow renaming and stale filename behaviour described here are covered by #80.
