### ISSUE TITLE
Files recorded and shared through SMS app are half the expected lenght

### ISSUE THREAD

**Issue by Cwpute** [FossifyOrg/Voice-Recorder#59]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Voice-Recorder/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Nokia TA-1157

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open a SMS conversation on Fossify SMS Messages 1.0.1
2. In the `+` menu select `Record audio`
3. Use Fossify Voice Recorder
4. Record an audio file

### Expected behavior

The audio file should be at its full lenght

### Actual behavior

The audio file is half its expected lenght.

I tested several times in a row. The first one lasted 30 seconds, but the final file was only 20 seconds long: it cut before the end. I thought it was a one time thing so i rerecorded a 20 second message, but this one as well got cut to 11sc. Determined to make it work, i tried a third time with a file that lasted 10 seconds: the result was 6 seconds long.
I closed the message app and tried recording a file directly by opening the Fossify Record app. The recording lasted 35 seconds and resulted in a 35 seonds long file, as expected.
I restarted my smartphone to see if it would fix it… and it did. I don't know what happened.

**Comment by Aga-C** [comment]
If restarting the phone has fixed it, then most probably it was a phone's glitch that's not reproducible.
